name: BasketballScrapeR
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.11.1
  - jsonschema=4.4.0
  - pandas=1.4.2
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pytz=2021.3
  - pyzmq=22.3.0
  - requests=2.27.1
  - scipy=1.7.3
  - soupsieve=2.3.1
  - urllib3=1.26.9
  - pip:
    - lxml==4.8.0
    - pyyaml==6.0
    - requests-toolbelt==0.9.1
    - tqdm==4.64.0
    - virtualenv==20.16.5
